'use strict'

/**
 * @fileoverview Shared JSDoc type definitions used across all CDH Bridge services.
 * These types mirror the Pega CDH data model and are used for documentation,
 * validation hints, and IDE autocompletion throughout the monorepo.
 */

/**
 * @typedef {Object} CustomerProfile
 * Represents a unified customer profile as stored/retrieved from Pega CDH.
 *
 * @property {string}   customerId   - Unique customer identifier (e.g. CDH subject ID)
 * @property {string}   email        - Primary email address
 * @property {string}   phone        - Primary phone number (E.164 format)
 * @property {string[]} segments     - Array of segment/audience labels (e.g. ['high-value', 'churn-risk'])
 * @property {number}   ltv          - Lifetime value estimate (currency units, numeric)
 * @property {ConsentRecord} consent - Nested consent flags for this customer
 * @property {string}   lastSeen     - ISO-8601 datetime of last known interaction
 * @property {string[]} sources      - Systems that have contributed data (e.g. ['salesforce', 'web'])
 */

/**
 * @typedef {Object} CdhEvent
 * Represents a behavioural or interaction event sent to or received from Pega CDH.
 *
 * @property {string} eventId      - UUID for this event (generated by event-collector)
 * @property {string} customerId   - Subject/customer this event belongs to
 * @property {string} eventType    - Semantic type (e.g. 'PageView', 'Purchase', 'FormSubmit')
 * @property {string} channel      - Originating channel ('web', 'mobile', 'email', 'call-centre')
 * @property {string} timestamp    - ISO-8601 datetime the event occurred
 * @property {Object} properties   - Arbitrary key-value bag of event-specific attributes
 * @property {Object} ihmapping    - Pega Interaction History mapping fields (ih_issue, ih_group, etc.)
 */

/**
 * @typedef {Object} ConsentRecord
 * Captures a customer's consent and privacy preferences across all channels.
 *
 * @property {string}   customerId    - Links back to the owning CustomerProfile
 * @property {boolean}  optOutEmail   - True if the customer has opted out of email marketing
 * @property {boolean}  optOutSms     - True if the customer has opted out of SMS
 * @property {boolean}  optOutPush    - True if the customer has opted out of push notifications
 * @property {boolean}  gdprErasure   - True if a GDPR right-to-erasure request is active
 * @property {boolean}  ccpaDoNotSell - True if the customer has invoked CCPA do-not-sell
 * @property {string}   updatedAt     - ISO-8601 datetime of last consent change
 * @property {string[]} propagatedTo  - List of systems to which this consent has been pushed
 */

/**
 * @typedef {Object} ConnectorConfig
 * Configuration for a third-party data source connector (Salesforce, Segment, GA4, etc.).
 *
 * @property {string} id            - UUID for this connector instance
 * @property {string} type          - Connector type key ('salesforce', 'segment', 'ga4', 'marketo', etc.)
 * @property {string} name          - Human-readable display name
 * @property {Object} credentials   - Connector-specific auth credentials (tokens, keys — never log these)
 * @property {string} syncMode      - 'full' | 'incremental' | 'real-time'
 * @property {Object} fieldMappings - Source field → CDH field mapping table
 * @property {string} lastSync      - ISO-8601 datetime of last successful sync
 * @property {string} status        - 'active' | 'paused' | 'error' | 'pending'
 */

/**
 * @typedef {Object} NBADecision
 * Represents a Next-Best-Action decision returned by Pega CDH Decision Management.
 *
 * @property {string} decisionId  - UUID generated by Pega for this decision
 * @property {string} customerId  - Customer the decision targets
 * @property {string} action      - The recommended action name (e.g. 'RetentionOffer')
 * @property {string} treatment   - Specific treatment/variant within the action
 * @property {string} outcome     - Decision outcome ('accepted', 'rejected', 'pending')
 * @property {string} channel     - Channel on which the decision should be surfaced
 * @property {string} timestamp   - ISO-8601 datetime the decision was generated
 */

// Factory helpers — lightweight constructors with sensible defaults.

/**
 * Build a CustomerProfile object with defaults applied.
 * @param {Partial<CustomerProfile>} overrides
 * @returns {CustomerProfile}
 */
function makeCustomerProfile(overrides = {}) {
  return {
    customerId: '',
    email: '',
    phone: '',
    segments: [],
    ltv: 0,
    consent: makeConsentRecord(),
    lastSeen: new Date().toISOString(),
    sources: [],
    ...overrides
  }
}

/**
 * Build a CdhEvent object with defaults applied.
 * @param {Partial<CdhEvent>} overrides
 * @returns {CdhEvent}
 */
function makeCdhEvent(overrides = {}) {
  return {
    eventId: '',
    customerId: '',
    eventType: '',
    channel: 'web',
    timestamp: new Date().toISOString(),
    properties: {},
    ihmapping: {},
    ...overrides
  }
}

/**
 * Build a ConsentRecord object with defaults applied (all opt-ins, no erasure).
 * @param {Partial<ConsentRecord>} overrides
 * @returns {ConsentRecord}
 */
function makeConsentRecord(overrides = {}) {
  return {
    customerId: '',
    optOutEmail: false,
    optOutSms: false,
    optOutPush: false,
    gdprErasure: false,
    ccpaDoNotSell: false,
    updatedAt: new Date().toISOString(),
    propagatedTo: [],
    ...overrides
  }
}

/**
 * Build a ConnectorConfig object with defaults applied.
 * @param {Partial<ConnectorConfig>} overrides
 * @returns {ConnectorConfig}
 */
function makeConnectorConfig(overrides = {}) {
  return {
    id: '',
    type: '',
    name: '',
    credentials: {},
    syncMode: 'incremental',
    fieldMappings: {},
    lastSync: null,
    status: 'pending',
    ...overrides
  }
}

/**
 * Build an NBADecision object with defaults applied.
 * @param {Partial<NBADecision>} overrides
 * @returns {NBADecision}
 */
function makeNBADecision(overrides = {}) {
  return {
    decisionId: '',
    customerId: '',
    action: '',
    treatment: '',
    outcome: 'pending',
    channel: 'web',
    timestamp: new Date().toISOString(),
    ...overrides
  }
}

// Validation helpers — lightweight structural checks.

/**
 * Validate that an object has the minimum required fields for a CdhEvent.
 * @param {any} obj
 * @returns {{ valid: boolean, errors: string[] }}
 */
function validateCdhEvent(obj) {
  const errors = []
  if (!obj || typeof obj !== 'object') { errors.push('event must be an object'); return { valid: false, errors } }
  if (!obj.eventId) errors.push('eventId is required')
  if (!obj.customerId) errors.push('customerId is required')
  if (!obj.eventType) errors.push('eventType is required')
  if (!obj.timestamp) errors.push('timestamp is required')
  return { valid: errors.length === 0, errors }
}

/**
 * Validate that an object has the minimum required fields for a CustomerProfile.
 * @param {any} obj
 * @returns {{ valid: boolean, errors: string[] }}
 */
function validateCustomerProfile(obj) {
  const errors = []
  if (!obj || typeof obj !== 'object') { errors.push('profile must be an object'); return { valid: false, errors } }
  if (!obj.customerId) errors.push('customerId is required')
  if (obj.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(obj.email)) errors.push('email format is invalid')
  if (!Array.isArray(obj.segments)) errors.push('segments must be an array')
  return { valid: errors.length === 0, errors }
}

module.exports = {
  makeCustomerProfile,
  makeCdhEvent,
  makeConsentRecord,
  makeConnectorConfig,
  makeNBADecision,
  validateCdhEvent,
  validateCustomerProfile
}
